name: "gigaam-v2-ctc"
platform: "onnxruntime_onnx"
max_batch_size: 8
version_policy: { all: {} }

input [
  {
    name: "features"
    data_type: TYPE_FP32
    dims: [64, -1]
  },
  {
    name: "feature_lengths"
    data_type: TYPE_INT64
    dims: [1]
    reshape: { shape: [] }
  }
]

output [
  {
    name: "log_probs"
    data_type: TYPE_FP32
    dims: [-1, 34]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]

dynamic_batching {
  preferred_batch_size: [1, 2, 4]
  max_queue_delay_microseconds: 2000
}
