server:
  port: 8090

spring:
  application:
    name: kafka-rest-producer

app:
  kafka:
    bootstrap-servers: "localhost:9092,localhost:9093,localhost:9094"

management:
  endpoints:
    web:
      exposure:
        include: "health,info"


