global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'triton'
    static_configs:
      - targets: ['triton-server:8002']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 4s
